config/routes.rb
Rails.application.routes.draw do
  get 'cards/show'
  resources :products
  get 'static_pages/index'
  get 'static_pages/secret'
  devise_for :users
  root 'shops#index'
  resources :carts
  resources :order_items
  resource :cards, only:[:show]
  resources :shops, only:[:index, :show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
    belongs_to :user, optional: true
    has_and_belongs_to_many :items
    
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
    has_many :order_items
    before_save :set_subtotal

    def subtotal
        order_items.collect{|order_item|order_item.valid? ? order_item.unit_price*order_item.quantity : 0}.sum
    end

    private

    def set_subtotal
        self[:subtotal] = subtotal   
    end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
    belongs_to :order
    belongs_to :product



    before_save :set_unit_price
    before_save :set_total

    def unit_price
        if persisted?
            self[:unit_price]
        else
            product.price
        end
    end


    def total
        unit_price*quantity
    end


    private

    def set_unit_price
        self[:unit_price] = unit_price
    end

    def set_total
        self[:total] = total * quantity
    end
end

app/models/product.rb
class Product < ApplicationRecord
    has_many :order_items
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one :cart
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include ApplicationHelper
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  def show
    @order_items = current_order.order_items
  end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
    def index
        @cart = Cart.all
      end
    
      def new
      end
    
      def create
      end
    
      def show
        @cart = Cart.find(params[:id])
      end
    
      def edit
      end
    
      def update
      end
    
      def destroy
      end
end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController

    def create
        @order = current_order
        @order_item = @order.order_items.new(order_params)
        @order.save
        session[:order_id] = @order.id
    end

    def update
        @order = current_order
        @order_item = @order.order_items.find(params[:id])
        @order_item.update_attributes(order_params)
        @order_items = current_order.order_items
    end

    def destroy
        @order = current_order
        @order_item = @order.order_items.find(params[:id])
        @order_item.destroy
        @order_items = current_order.order_items
    end


    private

    def order_params
        params.require(:order_item).permit(:product_id, :quantity)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]

  # GET /products or /products.json
  def index
    @products = Product.all
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:title, :price)
    end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  def index
    @products = Product.all

    @order_item = current_order.order_items.new
  end

  def show
    @product = Product.find(params[:id])
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :authenticate_user!, only: [:secret]
  def index
  end

  def secret
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

    def current_order
        if !session[:order_id].nil?
            Order.find(session[:order_id])
        else
            Order.new
        end
    end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/cards/_card.html.erb
<%= link_to "#{current_order.order_items.size} items with a value of #{current_order.subtotal }$", cards_path%>

app/views/cards/_cards_item.html.erb
<h1>Cards#show</h1>
<p>Find me in app/views/cards/show.html.erb</p>



<% @order_items.each do |item| %>

    <h3><%= item.product.title %></h3>
    <h5><%= item.product.price %></h5>


    <%= form_for item, remote: true do |f| %>
        <%= f.hidden_field :product_id, :value => item.product.id %>
        <%= f.number_field :quantity, :value => item.quantity.to_i %>
        <%= f.submit "Update Card "%>
        <%= link_to "Remove Items", order_item_path(item), method: :delete, remote: true%>
    <% end %>
    <h2>Subtotal: <%= item.total %></h2>

<% end %>




<h3>Your current card value has a subtotal of: <%= current_order.subtotal %></h3>

app/views/cards/show.html.erb
<div id="card-item">
<%= render 'cards_item'%>
</div>

app/views/order_items/create.js.erb
$('#card').html("<%= escape_javascript(render('cards/card'))%>")

app/views/order_items/destroy.js.erb
$('#card').html("<%= escape_javascript(render('cards/card'))%>")
$('#card-item').html("<%= escape_javascript(render('cards/cards_item'))%>")

app/views/order_items/update.js.erb
$('#card').html("<%= escape_javascript(render('cards/card'))%>")
$('#card-item').html("<%= escape_javascript(render('cards/cards_item'))%>")

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.title %></td>
        <td><%= product.price %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @product.title %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/shops/index.html.erb
<h1>Shops#index</h1>
<p>Find me in app/views/shops/index.html.erb</p>
<p id="notice"><%= notice %></p>

<h1>Products</h1>



<div class="row"> 
    <% @products.each do |product|%>
      <div class="col-lg-4 col-md-6 mb-4">
            <div class="card h-100">
              <a href="#"><img class="card-img-top" src ="https://mradio.fr/media/news/thumb/870x489_5c77973304410-le-chat-potte-06.jpg" alt=""></a>
              <div class="card-body">
                <h4 class="card-title">
                  <a href=""><%= product.title%></a>
                </h4>
                <%= link_to "En savoir plus", product_path(product.id), class: "btn btn-dark mr:10px" %>
                <h5><%= product.price%>$</h5>
                <%= form_for @order_item, remote: true  do |f|%>
                  <%= f.hidden_field :product_id, :value => product.id %>
                  <%= f.number_field :quantity, :value => 1, :min =>  1%>
                  <%= f.submit "Add to Card "%>
                  <% end %>
              </div>
              <div class="card-footer">
                <small class="text-muted">&#9733; &#9733; &#9733; &#9733; &#9734;</small>
              </div>
            </div>
          </div>
    <% end %>
</div>



<br>
<div id="card">
  <%= render 'cards/card'%>
</div>

app/views/shops/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @product.title %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<%= link_to 'Back', root_path %>

app/views/static_pages/index.html.erb
<ul>
  <% if user_signed_in? %>
    <li>
      <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
    </li>

    <li>
      Voici ton email : <%= current_user.email %>
    </li>

    <li>
      <%= link_to "Secret page", static_pages_secret_path %>
    </li>

    <li>
      <%= link_to "Edit email / password", edit_user_registration_path %>
    </li>

  <% else %>
    <li>    
      <%= link_to "Sign in", new_user_session_path %>
    </li>

    <li>
      <%= link_to "Sign up", new_user_registration_path %>
    </li>

  <% end %>
</ul>

app/views/static_pages/secret.html.erb
<div class="row py-5 px-4">
    <div class="col-md-5 mx-auto">
        <!-- Profile widget -->
        <div class="bg-white shadow rounded overflow-hidden">
            <div class="px-4 pt-0 pb-4 cover">
                <div class="media align-items-end profile-head">
                    <div class="profile mr-3"><img src="https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=80" alt="..." width="130" class="rounded mb-2 img-thumbnail"><a href="#" class="btn btn-outline-dark btn-sm btn-block">Edit profile</a></div>
                    <div class="media-body mb-5 text-white">
                        <h4 class="mt-0 mb-0">Mark Williams</h4>
                        <p class="small mb-4"> <i class="fas fa-map-marker-alt mr-2"></i>New York</p>
                    </div>
                </div>
            </div>
            <div class="bg-light p-4 d-flex justify-content-end text-center">
                <ul class="list-inline mb-0">
                    <li class="list-inline-item">
                        <h5 class="font-weight-bold mb-0 d-block">215</h5><small class="text-muted"> <i class="fas fa-image mr-1"></i>Photos</small>
                    </li>
                    <li class="list-inline-item">
                        <h5 class="font-weight-bold mb-0 d-block">745</h5><small class="text-muted"> <i class="fas fa-user mr-1"></i>Followers</small>
                    </li>
                    <li class="list-inline-item">
                        <h5 class="font-weight-bold mb-0 d-block">340</h5><small class="text-muted"> <i class="fas fa-user mr-1"></i>Following</small>
                    </li>
                </ul>
            </div>
            <div class="px-4 py-3">
                <h5 class="mb-0">About</h5>
                <div class="p-4 rounded shadow-sm bg-light">
                    <p class="font-italic mb-0">Web Developer</p>
                    <p class="font-italic mb-0">Lives in New York</p>
                    <p class="font-italic mb-0">Photographer</p>
                </div>
            </div>
            <div class="py-4 px-4">
                <div class="d-flex align-items-center justify-content-between mb-3">
                    <h5 class="mb-0">Recent photos</h5><a href="#" class="btn btn-link text-muted">Show all</a>
                </div>
                <div class="row">
                    <div class="col-lg-6 mb-2 pr-lg-1"><img src="https://images.unsplash.com/photo-1469594292607-7bd90f8d3ba4?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=750&q=80" alt="" class="img-fluid rounded shadow-sm"></div>
                    <div class="col-lg-6 mb-2 pl-lg-1"><img src="https://images.unsplash.com/photo-1493571716545-b559a19edd14?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=750&q=80" alt="" class="img-fluid rounded shadow-sm"></div>
                    <div class="col-lg-6 pr-lg-1 mb-2"><img src="https://images.unsplash.com/photo-1453791052107-5c843da62d97?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1350&q=80" alt="" class="img-fluid rounded shadow-sm"></div>
                    <div class="col-lg-6 pl-lg-1"><img src="https://images.unsplash.com/photo-1475724017904-b712052c192a?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=750&q=80" alt="" class="img-fluid rounded shadow-sm"></div>
                </div>
            </div>
        </div>
    </div>
</div>